<script src="//code.jquery.com/jquery-1.8.0.min.js"></script>
<script src="//malsup.github.com/jquery.form.js"></script>
<style type="text/css">
	td
	{
		margin-left:100cm;
		padding:10px;
		vertical-align:left;
	}
	.datafeeder-form input[type="text"] {
		width: 300px;
	}

	.fieldRowSelected {
		background-color: #45b5c1;
	}

	.text_td {
		padding-top: 6px;
		width: 117px;
	}

	.plus {
		background:url('http://unbxd.com/img/CircledPlus.png') no-repeat;
		height: 24px;
		width: 24px;
	}

	.minus {
		background:url('http://unbxd.com/img/CircledMinus.png') no-repeat;	
		height: 24px;
		width: 24px;
	}

	.hidden_image_textBox {
		display: none;
	}

	.form-list td.value select {
		width: 110px;
		}

	#field-list td {
		width: 120px;
	}

</style>
<script type="text/javascript">
        var $jq = jQuery.noConflict();
</script>
<frameset cols="50%,50%">
	<frame name="actual_frame">	
		<div class="datafeeder-form" onload="allset()">
			<form action="<?php echo $this->getSaveApiUrl();?>" method="POST" >

				<span><b>Unbxd API Key: </b><span>
				<input type="text" name="apikey" style="margin-left: 10px;" value="<?php echo $this->getApiKey(); ?>">
				<input type="submit" style="margin-left: 10px;" value="SAVE"/>
			</form>
            <form action="<?php echo $this->saveFeedConf();?>" method="POST" >
				<p class="switcher">
            	<label for="store_switcher"><b>Choose Store View: </b><label>

                <select id="site" class="site" name="site" onload="newajaxcall('<?php echo $this->getFeedConf(); ?>')" onchange="newajaxcall('<?php echo $this->getFeedConf();?>')">
                    <?php $allsites=Mage::app()->getWebsites();?>
                    <?php foreach ($allsites as $site):?>
                        <option value="<?php echo $site->getName()?>"><?php echo $site->getName()?></option>
					<?php endforeach;?>
				</select>
       			</p>


				<table class="form-list" onload="allset()" id="form-list1" name="form-list" cellspacing="0" style="background:none repeat scroll 0 0 #FAFAFA;border=1px solid #D6D6D6;width: 100%;" width="5000px">
				<div class="datafeeder-form" width="parent" style="background:none repeat scroll 0 0 #6F8992;padding:5px 10px; color: white;">
					FEED CONFIGURATION
				</div>
				<tr>
					<td class="label">
						<b>Unbxd Site Key: </b>
					</td>
					<td class="value">				
						<input type="text" id="siteName" name="siteName" value="" disabled/>
					</td>
					</tr>
				</tr>
				<tr>
					<td class="label">
					</td>
					<td class="value">
						<input type="button" name="editButton" value="EDIT"/> <input style="margin-left: 10px;" type="submit" value="SAVE"/>
					</td>
				</tr>
		</table>	
		
		<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
		</form>
		<script type="text/javascript">
	
		$jq('[name=editButton]').click(function(evt){
			$jq('[name="feedName"]').attr('disabled', false);
			$jq('[name="siteName"]').attr('disabled', false);
		});

		function progressbar()
		{
			$jq.ajax({
				  //async:false,
				  url: "<?php echo $this->getProgressUrl(); ?>",
				  type:"POST",
				  dataType:"json",
				  data:{"form_key":"<?php  echo Mage::getSingleton('core/session')->getFormKey()?>",
					"site": $jq('[name=site]').val()
					},
				  success: function(data) {
					  document.getElementById("ProgressBar").innerHTML="";
					  if(data.status=="0"){
					  	document.getElementById("ProgressBar").innerHTML="<b>Status: Indexed</b>";
					  	document.getElementById("fullupload").disabled=false;
					  }else if(data.status=="1"){
					  	document.getElementById("ProgressBar").innerHTML="<b>Status: Indexing</b>";
					  	document.getElementById("fullupload").disabled=true;
					  }
				  }
				});
			
		}
	
		function callSetInterval()
		{
			setInterval(progressbar,20000);	
		}
			
		function newajaxcall(ajaxurl){
		  		$jq.ajax({
					  
					  	url: ajaxurl,
					  	timeout:30000,
					  	type:"POST",
						dataType: "json",
					  	data:{"form_key":"<?php  echo Mage::getSingleton('core/session')->getFormKey()?>",
						"site":$jq('[name=site]').val(),
					},

					success: function(data) {
				
						if(data.feed !== "empty") $jq('[name=feedName]').val(data.feed); else $jq('[name=feedName]').val("");
						if(data.siteName !== "empty") $jq('[name=siteName]').val(data.siteName); else $jq('[name=siteName]').val("");
					},
					  
					fail: function(XMLHttpRequest, textStatus, errorThrown) {
					}	  
				});
			}
		
			newajaxcall("<?php echo $this->getFeedConf();?>");
		
			function makeajaxcall(ajaxurl){
		  
		    	$jq.ajax({
					
					url: ajaxurl,
					timeout:100000,
					type:"POST",
					data:{"form_key":"<?php  echo Mage::getSingleton('core/session')->getFormKey()?>",
						"site": $jq('[name=site]').val()
					},

					complete: function(xhr, statusText){	 
					},

					done: function(data) {
				        console.log(data);
					},
				
					fail: function(XMLHttpRequest, textStatus, errorThrown) {
					}	
				});
			}

			$jq('#config_edit_form').ready(function(){
				createTable('<?php echo $this->getEditUrl();?>');
		    });

			function saveFieldConf()
			{
				site = $jq('[name=site]').val();
				fields = {}
				$jq("#field-list").find("tr").each( function() { 
					var field = {};  
					if ($jq(this).find(".label").text() != "") {
						field["status"] = ($jq(this).find('[name=status]').find(":selected").text() == "Enabled") ? 1 :0; 
						field["autosuggest"] = ($jq(this).find('[name=autosuggest]').find(":selected").text() == "Enabled") ? 1 :0; 
						field["data_type"] = $jq(this).find('[name=dataType]').find(":selected").text(); 
						field["site_name"] = $jq('[name=site]').val();
						field["generate_image"] = $jq(this).find('[id=generate_image]').is(':checked')?1:0;
						element = this.querySelector('#image_height');
						if(element) {
							field["image_height"] = parseInt(element.value);
						} 
						element = this.querySelector('#image_width') ;
						if (element) {
							field["image_width"] = parseInt(element.value);
						}
						fields[$jq(this).find(".label").text()] = JSON.stringify(field);
						
						childProductField = {};
						if (this.className == "fieldRowSelected"){
							childProductField["status"] = field["status"];
						} else {
							childProductField["status"] = 0;
						}
						childProductField["autosuggest"] = field["autosuggest"];
						childProductField["data_type"] = field["data_type"];
						childProductField["site_name"] = field["site_name"];
						childProductField["generate_image"] = field["generate_image"];
						childProductField["image_width"] = field["image_width"];
						childProductField["image_height"] = field["image_height"];
 						fields[$jq(this).find(".label").text() + "Associated"] = JSON.stringify(childProductField);
							
						}
					});
			 	$jq.ajax({
				  	url: "<?php echo $this->getSaveFieldUrl();?>",
				  	timeout:30000,
				  	type:"POST",
					dataType: "json",
				  	data:fields
				}).done( function(data) {
					createTable('<?php echo $this->getEditUrl();?>');
				});
				
			}

			function createTable(ajaxurl)
			{
				site= $jq("#site").val();
				$jq.ajax({
					url: ajaxurl,
				  	type:"POST",
				  	data:{"site":site},
				}).done( function(data) {
					jarray = $jq.parseJSON(data);
					tableHtml="<tbody>";
					$jq("#field-list").find("tr").remove(); 
					tableHtml += addFieldConfTableHeader();
					$jq.each(jarray, function(key, value) {
							childExists = false;
							if ((key + "Associated") in jarray && jarray[key + "Associated"]["status"] == "1") {
								childExists = true
							}
							if( key.substr(-10) != "Associated" ) {
								tableHtml += constructRow(key, value, childExists);
							}
					  });
					tableHtml+="</tbody>";
					$jq('#field-list').append(tableHtml)
				  });	
			}

			function addFieldConfTableHeader() {
				return "<tr>" + 
					"<th>Field Name</th>" + 
					"<th>Status</th>" + 
					"<th>Data Type</th>" + 
					"<th>Autosuggest</th>" + 
					"<th>Add to configurable product</th>" + 
					"<th>Image configuration</th>" + 
					'<td class="scope-label"></td>' +
					"</tr>";
			}

			function constructRow(key, value, childExists) {
				tableString = "";
				tableString += '<tr ' + (childExists?'class="fieldRowSelected"':"") + '>';
				tableString += '<td class="label" name="fieldName"><div class="text_td">'+key+"</div></td>";
				tableString += constructBooleanSelect("status", value);
			  	tableString += constructDataType(key, value);
			  	tableString += constructBooleanSelect("autosuggest", value);
			  	tableString += constructAddToConfigurableFieldList(childExists);
			  	tableString += constructImageConf(key, value);
			  	tableString +='</tr>';
				return tableString;
			}

			function constructImageConf(key, value) {
				if(!("is_image" in value) || value["is_image"] != "true") {
					return "";
				}
				tableString = "";
				tableString += '<td><input type="button" value="EDIT" onclick="editImageConf(this)"/>'
				tableString += '<div class="hidden_image_textBox">';
				image_generation_enabled = (value["generate_image"] == 1)? true : false;
				tableString += '<input id="generate_image" onchange="toggleTextBox(this)" type="checkbox" ' + ((image_generation_enabled)?'checked':'')+'/>';
				tableString += '<input id="image_height" type="text" value="' + value["image_height"]+ '" '+ (image_generation_enabled? '':'disabled')+'"/>';
				tableString += '<input id="image_width" type="text" value="' + value["image_width"]+ '" '+ (image_generation_enabled? '':'disabled')+'"/>';
				tableString += '<input value = "update" type="button" onclick="hideDiv(this);"/>';
				tableString += '</div>';
				tableString += '</td>';
				return tableString;
			}

			function toggleTextBox(element) {
				active = element.checked ? false: true;
				element.parentElement.children[1].disabled = active;
				element.parentElement.children[2].disabled = active;
			}

			function hideDiv(element) {
				element.parentElement.parentElement.children[1].className = "hidden_image_textBox";
				element.parentElement.parentElement.children[0].className = "";
			}

			function editImageConf(element) {
				element.parentElement.children[1].className = "";
				element.className = "hidden_image_textBox";
			}

			function getRowSelected(element) {
				if(element.parentElement.parentElement.className == "fieldRowSelected") {
					element.parentElement.parentElement.className = "";
					element.children[0].className = "plus";
					return;
				}
				if($jq.find(".fieldRowSelected").length > 10) {
					alert("Cant select more than 10 fields");
					return;
				}
				element.children[0].className = "minus";
				element.parentElement.parentElement.addClassName("fieldRowSelected");
			}

			function constructAddToConfigurableFieldList(childExists) {
				tableString = '<td><a href="javascript:void(0)" onclick="getRowSelected(this)" title="Add this field in configurable/grouped product">';
				tableString += '<div ';
				if(!childExists) {
					tableString += 'class="plus"';
				} else {
					tableString += 'class="minus"';
				}
				tableString += "/></a></td>";
				return tableString;
			}

			function constructBooleanSelect(key, value) {
				tableString = '<td class="value"><div class="text_td"><select name=' + key + '>'+"<option";
				if(value[key]=="0"){
					tableString +=' selected="selected"';
				}
				tableString+=' value="0">Disabled</option><option';
				if(value[key]!="0"){
		            tableString +=' selected="selected"';
		        }
			  	tableString +=' value="1">Enabled</option></select></div></td>';
			  	return tableString;
			}

			function constructDataTypeOption(data_type, compare_data_type) {
				tableString  = "<option";

				if(data_type == compare_data_type){
					tableString +=' selected="selected"';
				}
				tableString+=' value="' + compare_data_type + '">' + compare_data_type + '</option>';
				return tableString;
			}

			function constructDataType(key, value) {
				tableString = '<td class="value"><div class="text_td"><select  name="dataType">'; 
				tableString += constructDataTypeOption(value["data_type"], "text");
				tableString += constructDataTypeOption(value["data_type"], "longText");
				tableString += constructDataTypeOption(value["data_type"], "link");
				tableString += constructDataTypeOption(value["data_type"], "decimal");
				tableString += constructDataTypeOption(value["data_type"], "number");
				tableString += constructDataTypeOption(value["data_type"], "date");
				//tableString += constructDataTypeOption(value["data_type"], "bool");

			  	tableString +='</select></div></td>';
				return tableString;
			}

			setInterval(progressbar,10000);
		</script>
      
		
		<table class="form-list" width="parent" id="form-list2" name="form-list" cellspacing="0" style="background:none repeat scroll 0 0 #FAFAFA;border=1px solid #D6D6D6;width: 100%;">
		 <div class="datafeeder-form" width="parent" style="background:none repeat scroll 0 0 #6F8992;padding:5px 10px;color: white;">
		     <div class="refreshDiv" style="float: right;"><span id="ProgressBar"></span><input type="button" id="refresh" onclick="progressbar()" value="REFRESH" style="margin-left: 10px;vertical-align: top;"></div>
				  <b>UPLOAD &amp; INDEX (manual)</b>
                </div>
					  
			<tr>						
				<td class="label"><b>PRODUCT FEED UPLOAD:  </b></td>
				<td class="value"><input type="button" id="fullupload" onclick="makeajaxcall('<?php echo $this->getFullIndexFormAction(); ?>')"  value="START"/></td>			
			
			</tr>	  
		    
	</table>
		
		<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>
	</div>
  </frame>
  <frame name="login_frame"></frame>
</frameset>

<div class="editconfig">
		<div class="content-header">
			<table cellspacing="0">
				<tr>
					<td>
						<h3 <?php if($this->getHeaderCss()): ?>
							class="<?php echo $this->getHeaderCss()?>" <?php endif; ?>>
							<?php echo Mage::helper('adminhtml')->__("FIELD CONFIGURATION") ?>
						</h3>
					</td>
					<td class="form-buttons">
						<input  type="button" style='background:url("images/btn_bg.gif") repeat-x scroll 0 100% #FFAC47;border-color:#ED6502 #A04300 #A04300 #ED6502;border-style:solid;border-width:1px;color:#FFFFFF;font:bold 12px arial,helvetica,sans-serif;text-align:center !important;white-space:nowrap;padding: 3px;' onclick="saveFieldConf()" value="SAVE"/>
					</td>
				</tr>
			</table>
		</div>
	    <div class="unbxd_edit_config" style="background:none repeat scroll 0 0 #FAFAFA;border:1px solid #D6D6D6">
		
			<form action="<?php echo $this->getSaveFieldUrl() ?>" method="post"
				id="config_edit_form" onload="createTable('<?php echo $this->getEditUrl();?>')">
				<input name="site_name" id= "site_name" type="hidden" />
					<!--<center>-->
				<p class="switcher">		
					<label for="store_switcher"><b> Field Configuration </b><label>
				</p>
				
				<table class="form-list" id="field-list" name="form-list" cellspacing="0" style="color: #2F2F2F;
			    font: 12px/1.5em Arial,Helvetica,sans-serif; margin-left: 1%;">
				</table>
				
				 <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />

			</form>
	    </div>
	</div>
