<script type="text/javascript">
    <?php $product = Mage::registry('current_product'); ?>
    var UnbxdWidgetsConf = {
        currency : "<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>"
        <?php if (isset($product)) { ?>
        ,pid:"<?php echo Mage::helper('unbxd_recommendation/feedhelper')->getUniqueId($product); ?>"
        <?php } ?>

    };
    <?php if(isset($product)) {
        $pid =  Mage::helper('unbxd_recommendation/feedhelper')->getUniqueId($product);;
     } ?>

    if (window.addEventListener) {
        window.addEventListener('load',
            function(){Unbxd.track("click",
                {"pid":"<?php echo Mage::helper('unbxd_recommendation/feedhelper')->getUniqueId($product); ?>",
                    rank: "", box_type: ""})}, false);
    } else {
        window.attachEvent('onload',
            function(){Unbxd.track("click",
                {"pid":"<?php echo Mage::helper('unbxd_recommendation/feedhelper')->getUniqueId($product); ?>",
                    rank: "", box_type: ""})});
    }
</script>