<?php $skinUrl =   Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN,
    Mage::app()->getFrontController()->getRequest()->isSecure())."/adminhtml/default/default/";
Mage::getBaseUrl()
?>
<input type="hidden" id="skinUrl" value="<?php echo $skinUrl; ?>" >

<script>
   try{
    window._unbxdSkinurl = "<?php echo $skinUrl; ?>"
    window._unbxdBaseurl = "<?php echo Mage::getUrl('',
    array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())) ?>"
   }catch(e){
    console.warn(e);
   }
    
</script>

<link rel="stylesheet" href= "<?php echo $skinUrl; ?>unbxd/css/bootstrap.css">
<link rel="stylesheet" href= "<?php echo $skinUrl; ?>unbxd/css/bootstrap-them.css">
<link rel="stylesheet" href= "<?php echo $skinUrl; ?>unbxd/css/chosen.css">
<link rel="stylesheet" href= "<?php echo $skinUrl; ?>unbxd/css/app.css">
<link rel="stylesheet" href= "<?php echo $skinUrl; ?>unbxd/css/unbxd-magento.css">


   <div id="container">
   </div>
   	
   	<script id='template' type='text/ractive'>
   			<div  class="unbxd-container height-100 parent">

   	   	<div class="magent0-left-nav width-17 pull-left height-100 unbxd-left">
   			 <div class="middle-nav-magento-dropdown height-100 unbxd-top-strip mar-btm-20">
				<div class="middle-nav-text mar-btm-10 pad-btm-0" style="padding-top: 10px;">
                Choose Website
                </div>

				<div class="middle-nav-dropdown mar-top-5 no-radius">
					<div class="btn-group width-100 unbxd-border" >
						 <select decorator='chosen:site' value={{site}} name="unbxd-site" id="selectSites">
						   	{{#sites}}
						   	<option value="{{name}}">{{name}}</option>
						   	{{/sites}}
						</select>
					</div>
				</div>
			</div>

			<div class="middle-nav-magento unbxd-left">
				<ul class="magento-nav">
					<li on-click='showCredentials' class="clickable-btn 
					{{#if _unbxdObject.activeStep.one}} magento-active{{/if}}">
						<a>Credentials</a> 
					</li>

					<li on-click='showCatalog' class="clickable-btn 
					{{#if _unbxdObject.activeStep.two}} magento-active{{/if}}">
						<a>Catalog</a> 
					</li>

					<li on-click='showAnalytics' class="clickable-btn
					{{#if _unbxdObject.activeStep.three}} magento-active{{/if}}">
						<a>Analytics</a> 
					</li>

					<li on-click='showWidgets' class="clickable-btn
					{{#if _unbxdObject.activeStep.four}} magento-active{{/if}}" >
						<a>Widgets</a> 
					</li>
				</ul>
			</div>
			
   		</div>

   		<div class="unbxd-right-div pull-left width-82 unbxd-right">
   			<div class="inner-container-magento row mar-0 top-185 pad-top-32 unbxd-top-strip">
					<div class="col-md-60 magento-row-tabs border-left-color pad-0 background-dark-grey unbxd-border ">
						<ul class="magento-conf-tabs">
							<li on-click='showCredentials'>
								<a  class="magento-conf-tabs-enabled 
									{{#if _unbxdObject.activeStep.one}}magento-head-active{{/if}} width-25  clickable-btn">
								<div class="magento-number" style="">
									1
								</div>
								<div class="magento-number-text">
									Authenticate App
								</div> </a>
							</li>
							<li on-click='showCatalog'>
								<a  class="magento-conf-tabs-enabled width-25 clickable-btn
								{{#if _unbxdObject.activeStep.two}}magento-head-active{{/if}}">
								<div class="magento-number">
									2
								</div>
								<div class="magento-number-text">
									 Catalog Configuration 
								</div> </a>
							</li>
							<li on-click='showAnalytics'>
								<a  class="magento-conf-tabs-enabled width-25 clickable-btn
								{{#if _unbxdObject.activeStep.three}}magento-head-active{{/if}}">
								<div class="magento-number">
									3
								</div>
								<div class="magento-number-text">
									Analytics integration
								</div> </a>
							</li>
							<li on-click='showWidgets'>
								<a  class="magento-conf-tabs-enabled width-25 clickable-btn
								{{#if _unbxdObject.activeStep.four}}magento-head-active{{/if}}" style="background-image:none;">
								<div class="magento-number">
									4
								</div>
								<div class="magento-number-text width-188">
									Install Recommendation Widget
								</div> </a>
							</li>
						</ul>
					</div>
			</div>

			<div id="innerContainr" class="inner-container-magento pad-btm-100 pad-top-20">
			</div>
   		</div>
	</div>
    </script>

 <script id='tab1Template' type='text/ractive'>
 </script>

 <script id='tab2Template' type='text/ractive'>
 </script>

 <script id='tab3Template' type='text/ractive'>
 </script>

  <script id='tab4Template' type='text/ractive'>
 </script>

 <script id='rowTemplate' type='text/ractive'>
 </script>


<script src= "<?php echo Mage::getBaseUrl('js',
        array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())).'/unbxd/jquery.js' ?>"></script>
<script src="<?php echo $skinUrl; ?>unbxd/js/lib/chosen.js"></script>
<script type="<?php echo $skinUrl; ?>text/javascript">
		 jQuery.noConflict();
</script>
<script src="<?php echo $skinUrl; ?>unbxd/js/lib/ractive.js"></script>
<script src="<?php echo $skinUrl; ?>unbxd/js/lib/ractive-chosen.js"></script>
<script src="<?php echo $skinUrl; ?>unbxd/js/lib/bootstrap-tooltip.js"></script>

<script src="<?php echo $skinUrl; ?>unbxd/js/app.js"></script>

	

