<?php
$searchModuleEnabled = Mage::helper('core')->isModuleEnabled('Unbxd_Searchcore');
$unbxdSearchenabled=false;
if($searchModuleEnabled) {
	$unbxdSearchenabled=true;
} else {
	$unbxdSearchenabled=false;
}

$unbxdSearch=false;
$unbxdRecs=false;
if(!Mage::helper("unbxd_recscore")->isExecutable()) { 
	$unbxdSearch = true;
} else {
	$unbxdRecs = true;
}
?>
<input type="hidden" id="auth" value="<?php echo Mage::getModel('unbxd_recscore/auth')->getAuthKey(); ?>">
<?php $skinUrl =   Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN,
    Mage::app()->getFrontController()->getRequest()->isSecure())."/adminhtml/default/default/";
Mage::getBaseUrl()
?>
<input type="hidden" id="skinUrl" value="<?php echo $skinUrl; ?>" >

<script>
   try{
   	window._unbxdConfigs = {};
   	_unbxdConfigs.unbxdSearchenabled = "<?php echo $unbxdSearchenabled; ?>"
   	_unbxdConfigs.unbxdRecsenabled = "1"
    window._unbxdSkinurl = "<?php echo $skinUrl; ?>"
    window._unbxdBaseurl = "<?php echo Mage::getUrl('',
    array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())) ?>"
	window._unbxdRecs = "<?php echo $unbxdRecs; ?>"
	window._unbxdSearch = "<?php echo $unbxdSearch; ?>"
	if(_unbxdRecs){
		_unbxdBaseurl = _unbxdBaseurl+ 'recscore';
	}else if(_unbxdSearch){
		_unbxdBaseurl = _unbxdBaseurl + 'searchcore';
	}
   }catch(e){
    console.warn(e);
   }
    
</script>

<link rel="stylesheet" href= "<?php echo $skinUrl; ?>unbxd/recscore/css/bootstrap.css">
<link rel="stylesheet" href= "<?php echo $skinUrl; ?>unbxd/recscore/css/bootstrap-them.css">
<link rel="stylesheet" href= "<?php echo $skinUrl; ?>unbxd/recscore/css/bootstrap-switch.css" >
<link rel="stylesheet" href= "<?php echo $skinUrl; ?>unbxd/recscore/css/chosen.css">
<link rel="stylesheet" href= "<?php echo $skinUrl; ?>unbxd/recscore/css/colpick.css">
<link rel="stylesheet" href= "<?php echo $skinUrl; ?>unbxd/recscore/css/app.css">
<link rel="stylesheet" href= "<?php echo $skinUrl; ?>unbxd/recscore/css/app1.css">
<link rel="stylesheet" href= "<?php echo $skinUrl; ?>unbxd/recscore/css/magento-app.css">
<link rel="stylesheet" href= "<?php echo $skinUrl; ?>unbxd/recscore/css/unbxd-magento.css">

   <div id="container">
   </div>

<script>
	var _unbxdLoadJquery = function( url, callback){

	if(  !window.jQuery || typeof window.jQuery === "undefined" || jQuery.fn.jquery < 1.7 ){

		var script = document.createElement("script")
		script.type = "text/javascript";

		if (script.readyState){  //IE
		script.onreadystatechange = function(){
		    if ( script.readyState == "loaded" || script.readyState == "complete" ){
		        script.onreadystatechange = null;
		        var library = jQuery.noConflict();
		        	callback(library);
		    }
		};
		} else {  //Others
		script.onload = function(){
		     var library = jQuery.noConflict();
		         callback(library);
		};
		}

		script.src = url;
		document.getElementsByTagName("head")[0].appendChild(script);

	}else{
		callback( window.jQuery );
		return false;
	}

   
};
_unbxdLoadJquery("<?php echo Mage::getBaseUrl('js',
        array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())).'/unbxd/recscore/jquery.js' ?>", function($){
	$.noConflict();

	var script = document.createElement("script")
		script.type = "text/javascript";
		script.setAttribute('data-main', "<?php echo $skinUrl; ?>unbxd/recscore/js/main");
		script.src = "<?php echo $skinUrl; ?>unbxd/recscore/js/lib/require.js";
		document.getElementsByTagName("head")[0].appendChild(script);
	
	});
</script>


