<input type="hidden" id="jQueryBaseUrl" value="<?php echo Mage::getBaseUrl('js',
    Mage::app()->getFrontController()->getRequest()->isSecure()) ?>unbxd/jquery.js"/>
<script type="text/javascript">
/* * * CONFIGURATION * * */
var UnbxdSiteName = "<?php echo Mage::getResourceModel('unbxd_recommendation/config')
->getValue(Mage::app()->getWebsite()->getId(), Unbxd_Recommendation_Helper_Confighelper::SITE_KEY) ?>";
var UnbxdApiKey = "<?php echo Mage::getResourceModel('unbxd_recommendation/config')
->getValue(Mage::app()->getWebsite()->getId(), Unbxd_Recommendation_Helper_Confighelper::API_KEY) ?>";

<?php $category = Mage::registry("current_category");
 if (isset($category)) { ?>
category = "<?php echo $category->getName(); ?>";
<?php } ?>

if(typeof UnbxdWidgetsConf == 'undefined' || UnbxdWidgetsConf == null) {
    var UnbxdWidgetsConf = {
        currency: "<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>"
        <?php if (isset($category)) { ?>
            ,category:"<?php echo $category->getName(); ?>"
        <?php } ?>
    };
}
/* * * DON'T EDIT BELOW THIS LINE * * */
(function() {
  var ubx = document.createElement('script'); 
  ubx.type = 'text/javascript'; ubx.async = true;
  ubx.src = '//d21gpk1vhmjuf5.cloudfront.net/magentoAnalytics.js';
  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ubx);
})();

(function() {
    var ubx = document.createElement('script');
    ubx.type = 'text/javascript'; ubx.async = true;
    ubx.src = '<?php echo Mage::getBaseUrl('js') ?>unbxd/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ubx);
})();

function getBaseUrl() {
    return "<?php echo Mage::getBaseUrl(); ?>";
}
</script>